### ISSUE TITLE
Permission page extends outside the screen

### ISSUE THREAD

**Issue by raymand211092** [MangoCubes/remotrix#17]
I can't continue from this screen....no i can see everything and I can't scroll to continue

Samsung galaxy a12

Android 13

![qfiohIGaMJtMRdugqvUwrqdN](https://github.com/MangoCubes/remotrix/assets/50679989/b8012594-437a-4d54-8c2c-519f85ed797c)

**Comment by MangoCubes** [comment]
I have created a temporary version that fixes this issue by making some pages that may have this kind of issue scrollable. It should be attached to this comment (it's zipped because Github won't accept .apk directly). Do let me know of any other issues you see. This fix will be included in the next version.
[v05alpha-scrollable.zip](https://github.com/MangoCubes/remotrix/files/12060147/v05alpha-scrollable.zip)
