### ISSUE TITLE
The RegEX for confirming management spaces is flawed

### ISSUE THREAD

**Issue by fbievan** [MangoCubes/remotrix#19]
https://github.com/MangoCubes/remotrix/blob/master/app/src/main/java/ch/skew/remotrix/setup/SetManagementSpace.kt

at line 130 the regex invalidates spaces made from conduit which uses numbers in its id scheme, a better regex for confirming whether something is a space needs to be made. 

I experienced this while trying to figure out why the bot was not sending the keys needed for decryption

**Comment by MangoCubes** [comment]
Ah, you mean something like this? 
```
{
  "room_id": "!abnjk1jdasj98:capuchins.com"
}
```
(Found in https://spec.matrix.org/v1.10/client-server-api/#put_matrixclientv3directoryroomroomalias)
Looks like Matrix standard got updated or I made weird assumptions. Either way, I will quickly make a fix. If it works, I will publish it as next minor release.

**Comment by MangoCubes** [comment]
I have made the changes and built the app. Please check if it works.
[app-release.zip](https://github.com/MangoCubes/remotrix/files/15148614/app-release.zip)
It's in ZIP because Github won't allow APK uploads. If you are getting invalid signature stuff, please uninstall the previous version. I lost the key used to sign that version... I know, this sounds somewhat shady. At least I made backups now and I won't lose it anymore.

**Comment by fbievan** [comment]
> I have made the changes and built the app. Please check if it works. [app-release.zip](https://github.com/MangoCubes/remotrix/files/15148614/app-release.zip) It's in ZIP because Github won't allow APK uploads. If you are getting invalid signature stuff, please uninstall the previous version. I lost the key used to sign that version... I know, this sounds somewhat shady. At least I made backups now and I won't lose it anymore.

Seems to work, other than the decryption issue (already denoted in another issue). 

I'll look into that to see if I can find the root cause. 

Why that assumption was made is because synpase from what I can tell *only* generates with letters.
